from mcpi.minecraft import Minecraft
mc=Minecraft.create()
x,y,z=mc.player.getPos()
def a(x,y,z,block):
    mc.setBlocks(x+1,y-1,z,x+3,y-1,z,block)
    mc.setBlocks(x+4,y-2,z,x+4,y-5,z,block)
    mc.setBlocks(x+3,y-3,z,x+1,y-3,z,block)
    mc.setBlocks(x+3,y-5,z,x+1,y-5,z,block)
    mc.setBlock(x,y-4,z,block)
def b(x,y,z,block):
    mc.setBlocks(x,y-1,z,x,y-7,z,block)
    mc.setBlock(x+1,y-4,z,block)
    mc.setBlocks(x+2,y-3,z,x+3,y-3,z,block)
    mc.setBlocks(x+4,y-4,z,x+4,y-6,z,block)
    mc.setBlocks(x+1,y-7,z,x+3,y-7,z,block)
def c(x,y,z,block):
    mc.setBlocks(x+3,y-1,z,x+1,y-1,z,block)
    mc.setBlocks(x,y-2,z,x,y-4,z,block)
    mc.setBlocks(x+1,y-5,z,x+3,y-5,z,block)
    mc.setBlock(x+4,y-2,z,block)
    mc.setBlock(x+4,y-4,z,block)
def d(x,y,z,block):
    mc.setBlocks(x+4,y-1,z,x+4,y-7,z,block)
    mc.setBlocks(x+1,y-7,z,x+3,y-7,z,block)
    mc.setBlocks(x,y-6,z,x,y-4,z,block)
    mc.setBlocks(x+1,y-3,z,x+2,y-3,z,block)
    mc.setBlock(x+3,y-4,z,block)
def e(x,y,z,block):
    mc.setBlocks(x+1,y-1,z,x+3,y-1,z,block)
    mc.setBlocks(x,y-2,z,x,y-4,z,block)
    mc.setBlocks(x+1,y-3,z,x+4,y-3,z,block)
    mc.setBlocks(x+1,y-5,z,x+4,y-5,z,block)
    mc.setBlock(x+4,y-2,z,block)
def f(x,y,z,block):
    mc.setBlocks(x,y-3,z,x+3,y-3,z,block)
    mc.setBlocks(x+1,y-2,z,x+1,y-7,z,block)
    mc.setBlocks(x+2,y-1,z,x+3,y-1,z,block)
def g(x,y,z,block):
    mc.setBlocks(x+1,y-1,z,x+4,y-1,z,block)
    mc.setBlocks(x,y-2,z,x,y-3,z,block)
    mc.setBlocks(x+1,y-4,z,x+4,y-4,z,block)
    mc.setBlocks(x+4,y-1,z,x+4,y-6,z,block)
    mc.setBlocks(x,y-7,z,x+3,y-7,z,block)
def h(x,y,z,block):
    mc.setBlocks(x,y-1,z,x,y-7,z,block)
    mc.setBlocks(x+4,y-7,z,x+4,y-4,z,block)
    mc.setBlocks(x+2,y-3,z,x+3,y-3,z,block)
    mc.setBlock(x+1,y-4,z,block)
def i(x,y,z,block):
    mc.setBlocks(x,y-3,z,x,y-7,z,block)
    mc.setBlock(x,y-1,z,block)
def j(x,y,z,block):
    mc.setBlocks(x,y-6,z,x,y-7,z,block)
    mc.setBlocks(x+1,y-8,z,x+3,y-8,z,block)
    mc.setBlocks(x+4,y-3,z,x+4,y-7,z,block)
    mc.setBlock(x+4,y-1,z,block)
def k(x,y,z,block):
    mc.setBlocks(x,y-1,z,x,y-7,z,block)
    mc.setBlock(x+1,y-5,z,block)
    mc.setBlock(x+2,y-4,z,block)
    mc.setBlock(x+2,y-6,z,block)
    mc.setBlock(x+3,y-3,z,block)
    mc.setBlock(x+3,y-7,z,block)
def l(x,y,z,block):
    mc.setBlocks(x,y-1,z,x,y-6,z,block)
    mc.setBlock(x+1,y-7,z,block)
def m(x,y,z,block):
    mc.setBlocks(x,y-1,z,x,y-5,z,block)
    mc.setBlocks(x+4,y-2,z,x+4,y-5,z,block)
    mc.setBlock(x+1,y-1,z,block)
    mc.setBlock(x+2,y-2,z,block)
    mc.setBlock(x+3,y-1,z,block)
a(x,y,z,57)
b(x+6,y+2,z,57)
c(x+12,y,z,57)
d(x+18,y+2,z,57)
e(x+24,y,z,57)
f(x+30,y+2,z,57)
g(x+35,y+1,z,57)
h(x+41,y+1,z,57)
i(x+47,y+1,z,57)
j(x+49,y+1,z,57)
k(x+55,y+1,z,57)
l(x+60,y+1,z,57)
m(x+63,y-1,z,57)